spring.application.name=${NAME}
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION}
mongodb_srv=${MONGODB_SRV}
spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE}
spring.mongodb.url=${SPRING_MONGODB_URL}





