spring.application.name=${NAME}
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION}
spring.data.uri=${MONGODB_SRV}
spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE:false}
#springdoc.swagger-ui.enabled=false
#springdoc.api-docs.enabled=false